name: PHP CI

on:
  push:
    branches:
      main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: Install Composer Deps
        run: composer install

      - name: Run debug
        run: composer debug

      # - name: Run PHPUnit test
      #   run: composer test
